version: "3.7"
services:

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile-ml-dev
    ports:
       - "127.0.0.1::8888"
    volumes:
       - ./:/pull-the-pitcher
    entrypoint: bash -c "cd /pull-the-pitcher && jupyter notebook --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash" 
    stdin_open: true
    container_name: "ptp_jupyter"
    tty: true
    env_file:
      - ./.env 

  bash:
    build:
      context: .
      dockerfile: Dockerfile-ml-dev
    volumes:
       - ./:/pull-the-pitcher
    entrypoint: "/bin/bash" 
    stdin_open: true
    container_name: "ptp_bash"
    tty: true
    env_file:
      - ./.env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    container_name: "ptp_streamlit"
    ports:
      - "8501:8501"

