version: "3.7"
services:

  bash:
    build:
      context: .
    volumes:
       - ./:/pull-the-pitcher
    entrypoint: "/bin/bash" 
    stdin_open: true
    container_name: "ptp_bash"
    tty: true
    env_file:
      - ./.env

  streamlit:
    build:
      context: .
    container_name: "ptp_streamlit"
    ports:
      - "8501:8501"

  db:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ptp_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  ptp_data:    
